// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_DATABASE_URL (Session pooler) para migrations - Transaction pooler trava no deploy
    url: process.env.DIRECT_DATABASE_URL || env("DATABASE_URL"),
  },
});
